### ISSUE TITLE
Change polling provider default threads from 1 to 20

### ISSUE THREAD

**Issue by ZNikke** [neicnordic/dcache-endit-provider#11]
The polling provider currently defaults to -threads=1, this is too low for anything except functional/developer tests.

Consequently, this should be changed to a more reasonable default. Earlier tests has shown that the big performance improvement happens when the thread count is increased to 20, so let's use that as the default instead.

As a reference, NDGF uses 200 threads on their production tape pools for absolute maximum performance when processing huge numbers of requests.

**Comment by krishna-veni** [comment]
Done. default threads value has been changed to 20 and README.md has been updated accordingly

**Comment by krishna-veni** [comment]
Closing the issue
