### ISSUE TITLE
Error while compiling the plugin

### ISSUE THREAD

**Issue by cristinamanzano** [neicnordic/dcache-endit-provider#6]
Hi,

I am trying to install the plugin for using it in a new dCache instance.

The compilation fails with the following error:

```
[ERROR] /root/dcache-endit-provider/src/main/java/org/ndgf/endit/AbstractEnditNearlineStorage.java:[137,24] method transformAsync in class com.google.common.util.concurrent.Futures cannot be applied to given types;
  required: com.google.common.util.concurrent.ListenableFuture<I>,com.google.common.util.concurrent.AsyncFunction<? super I,? extends O>,java.util.concurrent.Executor
  found: com.google.common.util.concurrent.ListenableFuture<java.lang.Void>,<anonymous com.google.common.util.concurrent.AsyncFunction<java.lang.Void,java.lang.Void>>
  reason: cannot infer type-variable(s) I,O
    (actual and formal argument lists differ in length)
```

As far as I see maven is using the right java version:

```
# mvn -version
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_342, vendor: Red Hat, Inc.
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.342.b07-1.el7_9.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-1160.76.1.el7.x86_64", arch: "amd64", family: "unix"
```

Maybe I am missing something obvious, could you please help me with this?

Thank you.

Cristina

**Comment by kofemann** [comment]
Looks like the issues is coming from PR https://github.com/neicnordic/dcache-endit-provider/pull/3. The new guava version have breaking changes

**Comment by cristinamanzano** [comment]
Thanks for taking a look, I can confirm that editing pom.xml and changing the version of guava to 24.1.1-jre fixes the problem.

**Comment by krishna-veni** [comment]
@cristinamanzano :- I have made code changes so that it is compatible with latest guava versions. You can use latest code and let me know if its working for you.
