### ISSUE TITLE
exception from getXattrs()?

### ISSUE THREAD

**Issue by yhshin** [neicnordic/dcache-endit-provider#9]
Hello, 

TRIUMF tested an adapted version of 1.0.9 with dCache 7.2.25, and got flush requests stuck.  It turned out that the following statement in `FlsushTask.java` was the source of the issue, and commenting out bypassed the issue.

```xattrs = request.getFileAttributes().getXattrs();```

Stuck flush meant that no flush requests were processed.  To track it, I put a few debug messages including the ones before and after the call.  The debug message before the call appeared only once from the first flush request and no other debug messages from FlushTask after it showed up at all.  There was no similar debug message from remaining flush requests.  So it seemed like that flush requests were stuck.  

There were still other debug messages from `WatchingEnditNearLineStorage` so the plugin seemed not crashed.  We tested flush requests only so we're not sure whether stage requests would have worked or not.

After more investigation, I found that `XATTR` was not defined so `guard()` raised `IllegalStateException`.  I wrapped the statement with if/else as a temporary fix.
 
The first question came to me was that were we the only site who have the issue?  If so, why XATTR was not defined in our case.  What does it need to fill the map? etc.

The second question is what happened to the exception?  I'm not a Java person so I just guess that somewhere above in the call stack did something or crashed(?) only that line?

Could you please enlighten me about it?

Thank you and kind regards, 
Yun-Ha

P.S. 
When I first adapted Endit when Gerd introduced this wonderful plugin, I changed `activate()` to `activateWithPath()` to gurantee that we're able to get `path` info all the time.  If I remember correctly, at that time it was not guaranteed that `path` info was not always available in `StorageInfo`.  I don't think that results in undefined XATTR but that's the only technical difference.

It seems that now you're extracting path info from `StorageInfo`.  Is `path` always in `StorageInfo` now?  If so, I'd like to change it back to simple `activate` method.

**Comment by krishna-veni** [comment]
Hi @yhshin :- I have reverted Xattrs() changes. NDGF had similar issue with Xattrs(). Can you test the latest master and let me know

**Comment by krishna-veni** [comment]
Xattrs() has been removed. Closing the issue.

**Comment by yhshin** [comment]
HI Krishna,

Thank you for the update.
I will ask my site's dcache expert to test it and let you know when he gets
the result..

Kind regards,
Yun-Ha
